image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t my-site-image .
    - docker run -d --name my-site-container --entrypoint sleep my-site-image 3600
    - docker exec my-site-container ls /app/public # Debug: Verify directory
    - docker cp my-site-container:/app/public ./public
    - docker stop my-site-container
    - docker rm -f my-site-container
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH