image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t my-site-image .
    - docker run -d --name my-site-container my-site-image
    - docker cp my-site-container:/app/public ./public
    - docker stop my-site-container
    - docker rm my-site-container
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH