name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Trigger on push to the main branch
  pull_request:
    branches:
      - master   # Trigger on pull request to main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9 as in your GitLab example

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest ./src/test_app.py  # Adjust to your test file path

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/simoncharvat/streamlit_app:${{ github.ref_name }}-${{ github.sha }} .
      
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/simoncharvat/streamlit_app:${{ github.ref_name }}-${{ github.sha }}
